<?php

declare(strict_types=1);

use Drupal\Core\Form\FormStateInterface;

/**
* Implements hook_theme_suggestions_form_alter().
*/
function garden_journal_theme_suggestions_form_alter(array &$suggestions, array $variables): void {
  if(isset($variables['element']['#form_id'])) {
    $suggestions[] = 'form__' . $variables['element']['#form_id'];
  }  
}

/**
 * Implements hook_form_alter() for form.
 */
function garden_journal_form_alter(array &$form, FormStateInterface $form_state, string $form_id): void {
  // Define the default classes applied to all forms.
  $form_classes = [
    'form',
    'panel',
  ];

  // Add the default classes while preserving existing form classes.
  $form['#attributes']['class'] = array_merge(
    $form['#attributes']['class'] ?? [], $form_classes
  );

  // Define form IDs that use a narrower layout.
  $thinner_forms = [
    'user_login_form',
    'user_pass',
    'user_register_form',
  ];

  // Add the 'extra-thin' class to forms with a narrower layout.
  if (in_array($form_id, $thinner_forms, TRUE)) {
    $form['#attributes']['class'][] = 'extra-thin';
  }
}

/**
 * Implements hook_preprocess_HOOK() for input.
 */
function garden_journal_preprocess_input(array &$variables): void {
  if (!isset($variables['element']['#type']) || $variables['element']['#type'] !== 'submit') {
    return;
  }

  // Add 'button--primary' class to submit buttons by default.
  $variables['attributes']['class'][] = 'button--primary';
}

/**
 * Implements hook_preprocess_HOOK() for page.
 */
function garden_journal_preprocess_page(array &$variables): void {
  $variables['container'] = TRUE;
}

/**
 * Implements hook_form_views_exposed_form_alter().
 */
function garden_journal_form_views_exposed_form_alter(array &$form): void {
  // Attach the exposed_form_search library when the Search API fulltext search
  // is present in the exposed form. 
  if (isset($form['keyword'])) {
    $form['#attached']['library'][] = 'garden_journal/exposed_form_search';
  }
}
